CREATE TABLE app_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider         VARCHAR(20)  NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    display_name     VARCHAR(255) NOT NULL,
    email            VARCHAR(255),
    avatar_url       VARCHAR(500),
    created_at       TIMESTAMP    NOT NULL,
    last_login_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_app_user_provider UNIQUE (provider, provider_user_id)
);
